### PR TITLE
add syncmethod decorator to disconnect method

### PR DESCRIPTION
**Pull request by ghilesdev**

### CODE REVIEW

**Comment by oroulet** [comment]
Are you sure? Looks like that method is manually implemented for some reasons...

**Comment by okapies** [comment]
@ghilesdev I recommend you check how is `syncmethod` implemented. `disconnect` additionally needs to `stop` the thread loop for synchronization after it is called.

https://github.com/FreeOpcUa/opcua-asyncio/blob/c2482f8d7aff4f9ab05053ea872158d15a0004cb/asyncua/sync.py#L104-L114

**Comment by ghilesdev** [comment]
> Are you sure? Looks like that method is manually implemented for some reasons...

the reason why I added this decorator is that when I call the disconnect() I got error that says that disconnect was never awaited, and adding that decorator solved the problem

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\codes\tools\tools_packages\_hw_communication\src\_hw_communication\opcua_client.py", line 62, in _check_connection_in_thread
    self.connect_to_plc()
  File "C:\codes\tools\tools_packages\_hw_communication\src\_hw_communication\opcua_client.py", line 55, in connect_to_plc
    self.connect()
  File "C:\codes\tools\.venv\lib\site-packages\asyncua\sync.py", line 96, in wrapper
    result = self.tloop.post(aio_func(*args, **kwargs))
  File "C:\codes\tools\.venv\lib\site-packages\asyncua\sync.py", line 52, in post
    raise ThreadLoopNotRunning(f"could not post {coro}")
asyncua.sync.ThreadLoopNotRunning: could not post <coroutine object Client.connect at 0x000001CAEF921240>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\codes\tools\tools_packages\_hw_communication\src\_hw_communication\opcua_client.py", line 70, in disconnect
    self.tloop.post(self.aio_obj.disconnect())
  File "C:\codes\tools\.venv\lib\site-packages\asyncua\sync.py", line 52, in post
    raise ThreadLoopNotRunning(f"could not post {coro}")
asyncua.sync.ThreadLoopNotRunning: could not post <coroutine object Client.disconnect at 0x000001CAEF96BCC0>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python39\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Python39\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "C:\codes\tools\tools_packages\_hw_communication\src\_hw_communication\opcua_client.py", line 64, in _check_connection_in_thread
    self.disconnect()
  File "C:\codes\tools\tools_packages\_hw_communication\src\_hw_communication\opcua_client.py", line 73, in disconnect
    self.tloop.stop()
  File "C:\codes\tools\.venv\lib\site-packages\asyncua\sync.py", line 46, in stop
    self.loop.call_soon_threadsafe(self.loop.stop)
  File "C:\Python39\lib\asyncio\base_events.py", line 791, in call_soon_threadsafe
    self._check_closed()
  File "C:\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
C:\Python39\lib\threading.py:975: RuntimeWarning: coroutine 'Client.disconnect' was never awaited
  self._invoke_excepthook(self)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
C:\Python39\lib\threading.py:975: RuntimeWarning: coroutine 'Client.connect' was never awaited
  self._invoke_excepthook(self)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback```

**Comment by ghilesdev** [comment]
okay sorry for wasting your time, I understood how the disconnect() works, and the problem came from my custom class that inherits from sync.Client()

**Pull request closed without merging**
