### PR TITLE
Update Nodeset to 1.04.10

### PR DESCRIPTION
**Pull request by schroeder-**
- Reading Locale in Nodeset fixed.
- Fix model comparison, comparing against 1.04.10 failed
- UaBinary: Allow fields in struct with "AllowSubtypes" 
- Handle DataSetFieldFlags and other Flags with Length != 4 Byte

### CODE REVIEW

**Comment by schroeder-** [comment]
Ok I run in to mypy issues. There where some ignore hints places with #833 in asyncua/ua/uaprotocol_auto.py that are removed when generating the new types.

**Comment by oroulet** [comment]
Arrg i was afraid of that MR. I should have seen that. I can revert if we need to

**Comment by schroeder-** [comment]
Maybe we can work around this, I will look into it.

**Comment by schroeder-** [comment]
Currently its only the Union class, i added a list for mypy ignore classes.

**Comment by schroeder-** [comment]
@[oroulet](https://github.com/oroulet) is there anything that blocks the merge? I need the changes for my pubsub branch.

**Comment by oroulet** [comment]
Sorry forgot that one

**Pull request merged**
