### PR TITLE
Fix #1634

### LINKED ISSUE #1634: VariantType and SecurityPolicyType should be IntEnum
**Describe the bug** <br />
Attempts to serialize an object with SecurityPolicyType or VariantType attributes fail. Enums cannot be serialized. Changing them to IntEnum makes them serializable, plus they are already effectively IntEnums based on their implementation (i.e. `named_attribute = int`).

**To Reproduce**<br />
```python
import json
from asyncua.ua import VariantType, SecurityPolicyType

json.dumps({"variant": VariantType.Boolean, "security_policy": SecurityPolicyType.None})

>>> `TypeError: Object of type VariantType is not JSON serializable`
OR
>>> `TypeError: Object of type SecurityPolicyType is not JSON serializable`
```

**Expected behavior**<br />
Serialization to succeed.

**Version**<br />
Python-Version:3.12
opcua-asyncio Version (e.g. master branch, 0.9): 1.1.0

### PR DESCRIPTION
**Pull request by dakotahorstman**
Also:

- Fix SecurityPolicyType docstring: e.g. "None" -> "NoSecurity"
- Reorganize imports and better align code to pep standards (ruff)

Note: The following tests did not work prior to this PR on my local computer:
- `FAILED tests/test_server.py::test_runTest - assert None == 123`

- `FAILED tests/test_xml.py::test_xml_import_companion_specifications[client] - FileNotFoundError: [Errno 2] No such file or directory: '/home/user/Documents/opcua-asyncio/nodeset/DI/Opc.Ua.Di.NodeSet2.xml'`

- `FAILED tests/test_xml.py::test_xml_import_companion_specifications[server] - FileNotFoundError: [Errno 2] No such file or directory: '/home/user/Documents/opcua-asyncio/nodeset/DI/Opc.Ua.Di.NodeSet2.xml'`

### CODE REVIEW

**Comment by oroulet** [comment]
Generally it would be really great if you would not mix real changes with formatting changes, it makes code review almost impossible.
Also are you sure about None? as far as I remember None is how NoSecurity is mentionned everywhere in spec. I agree it is more precise though...

**Comment by dakotahorstman** [comment]
I changed "None" to "NoSecurity" to align with the attributes of the enum, along with the removal of underscores of others in the docstring. If the spec outlines "None", then would it be better to note the name discrepancy (since None is a reserved name in Python).

I can undo the format changes if you'd like.

**Comment by dakotahorstman** [comment]
> > Note: The following tests did not work prior to this PR on my local computer:
> > ```
> > * `FAILED tests/test_server.py::test_runTest - assert None == 123`
> > 
> > * `FAILED tests/test_xml.py::test_xml_import_companion_specifications[client] - FileNotFoundError: [Errno 2] No such file or directory: '/home/user/Documents/opcua-asyncio/nodeset/DI/Opc.Ua.Di.NodeSet2.xml'`
> > 
> > * `FAILED tests/test_xml.py::test_xml_import_companion_specifications[server] - FileNotFoundError: [Errno 2] No such file or directory: '/home/user/Documents/opcua-asyncio/nodeset/DI/Opc.Ua.Di.NodeSet2.xml'`
> > ```
> 
> This happens to me as well, and I think it's because `nodeset` is a git submodule. What happens if you run below in repo root? `git submodule update --init`

This fixed two of the tests, but `test_runTest` is still throwing an assertion error same as before. I appreciate the correction :)

**Comment by oroulet** [comment]
formatting changes are fine, but it makes reading diff much easier of they are in their own commits

**Comment by oroulet** [comment]
Also I am afraid renaming None will break existing code, so I am not sure we can do that

**Comment by dakotahorstman** [comment]
Sorry, let me clarify.

All I mean is something like this:

```python
class SecurityPolicyType(IntEnum):
    """
    The supported types of SecurityPolicy.

    Note: The OPC spec uses the keyword "None" to refer to a
    non-signed, non-encrypted endpoint. Because "None" is a reserved
    Python name, we've used "NoSecurity" in its stead. In other words,
    "NoSecurity" here is the same as "None" in the OPC spec.

    "NoSecurity"
    "Basic128Rsa15_Sign"
    "Basic128Rsa15_SignAndEncrypt"
    "Basic256_Sign"
    "Basic256_SignAndEncrypt"
    "Basic256Sha256_Sign"
    "Basic256Sha256_SignAndEncrypt"
    "Aes128Sha256RsaOaep_Sign"
    "Aes128Sha256RsaOaep_SignAndEncrypt"
    "Aes256Sha256RsaPss_Sign"
    "Aes256Sha256RsaPss_SignAndEncrypt"
    """

    NoSecurity = 0
```

**Pull request merged**
