### PR TITLE
fix missing async in server-callback.py

### PR DESCRIPTION
**Pull request by AndreasHeine**

### CODE REVIEW

**Comment by AndreasHeine** [comment]
how does this ever work? ;)

**Comment by oroulet** [comment]
wating for the other callback PR to be merged. Then this one must be updated too

**Comment by AndreasHeine** [comment]
ok

**Comment by oroulet** [comment]
@AndreasHeine nowit is merged. you need to update some names I think

**Comment by AndreasHeine** [comment]
https://github.com/FreeOpcUa/opcua-asyncio/pull/229/files

@oroulet doesn't look like the api has changed, i would add the three new callbacktypes!

**Pull request merged**
