### PR TITLE
Add async and await for call Method in InternalSession class

### PR DESCRIPTION
**Pull request by swamper123**

### CODE REVIEW

**Comment by oroulet** [comment]
Ops supert i never ment you should create so many pull requests. But in you last request you had both adding async and other things. You can add all related async things in one pull request

**Comment by oroulet** [comment]
Sorry I meant. Not super ;-)

**Comment by swamper123** [comment]
*sigh, grabs keyboard again* ;-)
Than it was a misunderstood, sorry.
I will make a single one later today.

**Comment by swamper123** [comment]
#206

**Pull request closed without merging**
