### PR TITLE
remove use of loop paramter in Client as of current asynio best pract…

### PR DESCRIPTION
**Pull request by oroulet**
…ices

### CODE REVIEW

**Comment by oroulet** [comment]
@ZuZuD that changes breaks the Uaclient . I was unsure how you want to change it. Can you have a look?

**Comment by oroulet** [comment]
@ZuZuD I tried fixing the ha:client... tests pass but they are many asyncio warning... maybe they were there anyway...

**Comment by ZuZuD** [comment]
@oroulet I will try to have a look by this evening.

**Comment by oroulet** [comment]
tests are passing so I am merging, but nice if you have a look

**Pull request merged**
