### PR TITLE
enable mypy

### PR DESCRIPTION
**Pull request by vruge**
- mirror change from mypy
- ignore mypy errors
  - better to fix issues step by step
  
## rough summary of the errors ( not complete )

```python
# I'm not find stubs package for mypy
from sortedcontainers import SortedDict  # type: ignore

# Optinal[String]
ProductUri: String = None  # type: ignore

# "frozen" argument must be True or False. I guess it's false posetive 
disable_error_code = misc

# Name "SubHandler" already defined (possibly by an import)  [no-redef]
class SubHandler(SubHandler):  # type: ignore
# asyncua/ua/uaprotocol_auto.py:2579: error: Name "Union" already defined (possibly by an import)  [no-redef]
# asyncua/common/connection.py:12: error: Name "InvalidSignature" already defined (possibly by an import)  [no-redef]
class Union:  # type: ignore


# Cannot find implementation or library stub for module named "IPython"
from IPython import embed  # type: ignore

# Argument 1 to "NodeId" has incompatible type "int"; expected "Union[Int32, String, Guid, ByteString]"
# "FourByteNodeId" has incompatible type "int"; expected "Union[Int32, String, Guid, ByteString]"
disable_error_code = arg-type


# asyncua/client/ha/reconciliator.py:384: error: "Reconciliator" has no attribute "hook_add_to_map_error"  [attr-defined]
# asyncua/client/ha/reconciliator.py:411: error: "Reconciliator" has no attribute "hook_add_to_map"; maybe "add_to_map"?  [attr-defined]
# asyncua/client/ha/reconciliator.py:432: error: "Reconciliator" has no attribute "hook_del_from_map"; maybe "del_from_map"?  [attr-defined]
disable_error_code = attr-defined


# asyncua/ua/uaerrors/_base.py:39: error: Need type annotation for "_subclasses" (hint: "_subclasses: Dict[<type>, <type>] = ...")  [var-annotated]
# asyncua/server/address_space.py:42: error: Need type annotation for "datachange_callbacks" (hint: "datachange_callbacks: Dict[<type>, <type>] = ...")  [var-annotated]
disable_error_code = var-annotated


# asyncua/ua/uatypes.py:311: error: Incompatible types in assignment (expression has type "int", variable has type "UInt32")  [assignment]
# asyncua/ua/uatypes.py:380: error: Incompatible types in assignment (expression has type "int", variable has type "Union[Int32, String, Guid, ByteString]")  [assignment]
# asyncua/ua/uatypes.py:381: error: Incompatible types in assignment (expression has type "int", variable has type "Int16")  [assignment]

disable_error_code = attr-defined


# asyncua/server/address_space.py:379: error: Item "None" of "Optional[Variant]" has no attribute "Value"  [union-attr]
# asyncua/server/address_space.py:460: error: Item "None" of "Optional[Variant]" has no attribute "Value"  [union-attr]
# asyncua/server/address_space.py:465: error: Item "None" of "Optional[Variant]" has no attribute "Value"  [union-attr]
# asyncua/server/address_space.py:468: error: Item "None" of "Optional[Variant]" has no attribute "Value"  [union-attr]

disable_error_code = union-attr


# asyncua/common/xmlimporter.py:278: error: Name "NodeId" is not defined  [name-defined]
# asyncua/common/xmlimporter.py:278: error: Name "QualifiedName" is not defined  [name-defined]
def _to_migrated_nodeid(self, nodeid: Union[ua.NodeId, None, str]) -> Union[ua.NodeId, ua.QualifiedName]:

# asyncua/client/ua_client.py:44: error: Argument 1 of "connection_made" is incompatible with supertype "BaseProtocol"; supertype defines the argument type as "BaseTransport"  [override]
# asyncua/client/ua_client.py:48: error: Argument 1 of "connection_lost" is incompatible with supertype "BaseProtocol"; supertype defines the argument type as "Optional[Exception]"  [override]
disable_error_code = override

# asyncua/server/address_space.py:645: error: Value of type variable "SupportsRichComparisonT" of "sorted" cannot be "Union[Int32, String, Guid, ByteString]"  [type-var]
identifier_list = sorted(  # type: ignore

# asyncua/common/subscription.py:224: error: Incompatible return value type (got "Union[int, List[Union[int, StatusCode]]]", expected "int")  [return-value]
return await self._subscribe(sourcenode, ua.AttributeIds.EventNotifier, evfilter, queuesize=queuesize)  # type: ignore
# asyncua/common/subscription.py:255: error: Incompatible return value type (got "Union[int, List[Union[int, StatusCode]]]", expected "int")  [return-value]
return await self._subscribe(sourcenode, ua.AttributeIds.EventNotifier, evfilter, queuesize=queuesize)  # type: ignore


# asyncua/common/subscription.py:466: error: List item 0 has incompatible type "Optional[int]"; expected "UInt32"  [list-item]
params.SubscriptionIds = [self.subscription_id]  # type: ignore
# asyncua/common/structures104.py:47: error: List item 0 has incompatible type "int"; expected "UInt32"  [list-item]
field.ArrayDimensions = [1]  # type: ignore

# asyncua/server/internal_server.py:136: error: Missing return statement  [return]
async def _address_space_fixes(self) -> Coroutine:  # type: ignore

# asyncua/common/structures104.py:358: error: Unsupported target for indexed assignment ("None")  [index]
new_objects[dts.name] = env[dts.name]  # type: ignore

# asyncua/client/client.py:180: error: "SecurityPolicy" not callable  [operator]
self.security_policy = policy(server_cert, cert, pk, mode)  # type: ignore
```

### CODE REVIEW

**Comment by vruge** [comment]
@oroulet I need some help. I don't understand the error inside "Code scanning results / CodeQL".

**Comment by oroulet** [comment]
@vruge I have no ideas what this is about, seems to be some security stuff but it complains about things you do not seems to have change, and I do not see where the secrity issue is. looks lke the scanner things logging the server itself will leak the certificate, it does not since it only prints name and port.
I am tring to find out how to disable that one

**Comment by oroulet** [comment]
Is that PR readay to be merged? Jsut wondering if I should go through it, there are so many changes...

**Comment by vruge** [comment]
> Is that PR readay to be merged? Jsut wondering if I should go through it, there are so many changes...

yes. The PR is probably very small in proportion if we/I/you/somebody enable partial the check of mypy:
`arg-type, attr-defined, assignment, union-attr, var-annotated, override`
which are disabled in `setup.cfg` now.

**Comment by swamper123** [comment]
I guess this is the part he is ocmplaining about
https://github.com/FreeOpcUa/opcua-asyncio/security/code-scanning/12

Perhaps he is complaining, that the lines mentioned below in the list are possibly logged as well.
It's about the `self` in the logging, since you may publish information you may not want to be logged.

But this has nothing to do with this PR, that is a more general thing.

**Pull request merged**
