### PR TITLE
add test showing new bug

### PR DESCRIPTION
**Pull request by oroulet**

### CODE REVIEW

**Comment by oroulet** [comment]
@schroeder- looks like your commit form a few days ago introduces a regression that was not catched by our tests. see my commit in this PR. I am a bit lost in what is happening here, so if you have an idea it would be nice https://github.com/FreeOpcUa/opcua-asyncio/commit/2b64f0f16fe9d27d62321f00aa40182c673d8ac8

**Comment by schroeder-** [comment]
Will look into it

**Comment by schroeder-** [comment]
See #898

**Comment by oroulet** [comment]
thanks @schroeder- !

**Pull request closed without merging**
