### PR TITLE
Draft: Improve history reading

### PR DESCRIPTION
**Pull request by HarrySky**
See #558

Should be backwards compatible. Changes:
- Make `ReturnBounds` parameter configurable
- Make possible to read history recursively with `recursive` argument

### CODE REVIEW

**Comment by HarrySky** [comment]
Instead of recursive argument - separate method could be created

**Comment by oroulet** [comment]
Is there any reason not to have recursive True all the time? I mean this is a high level method, users expect it to return all requested data. I think all high level browse methods work that way. If several calls are needed they do it anyway

**Comment by HarrySky** [comment]
I tried not to break existing codebases that don't expect recursive behaviour :smile:

**Comment by oroulet** [comment]
I am rather sure, people using that method expected a recursive behavior. Just did not think that there might be cases where the server does not answer everything.
I would remove the recursive option and make it behave recursively in all cases

**Comment by HarrySky** [comment]
Done, made it recursive by default without argument

**Comment by HarrySky** [comment]
It seems that there are some problems with server code if recursive is the default. Client works from that commit as expected

**Comment by HarrySky** [comment]
Just in case, I use https://github.com/open62541/open62541 as OPC UA server

**Comment by oroulet** [comment]
What symptoms?

**Comment by HarrySky** [comment]
I mean CI failed here on some server code if I understood logs correctly

**Comment by HarrySky** [comment]
So, should I bring back `recursive=False`? Or can we fix server tests somehow?

**Comment by oroulet** [comment]
your code looks correct, so we really should fix the server...

**Comment by HarrySky** [comment]
After quick search I found a possible problem: #322 (not sure, though, but maybe history is piling up from other tests and when we read it recursively - it gives more records). I do not know much about asyncua server, to be honest

**Comment by oroulet** [comment]
I had a look and I thinnk th eserver is not beahving correctly. It returns a ContinuationPoint when it should not. It always a return a ContinuationPoint if NumValuesPerNode is specified, it should probably not. It will need to be fixed.
https://github.com/FreeOpcUa/opcua-asyncio/blob/d2ba37e3dd0d9a8e054fac7f15be4b8dd34d1066/asyncua/server/history.py#L147

As far as I understand the conitnuation poitns has to be used only dues to internal server limitations, we do not have any so we should never return one OR maybe set a reasonable value there such as as 100000 for example

**Comment by HarrySky** [comment]
Yeah, in my case server sends maximum N values to one history read request. So I need to use `ContinuationPoint` to read all the data available

**Comment by oroulet** [comment]
do you se N yourself or is it something the server has decided? what is the value of N?

**Comment by HarrySky** [comment]
Server sets it, N can be anything, for testing we currently use N=100

```cpp
/* We want the server to serve a maximum of 100 values per request. This
 * value depend on the plattform you are running the server. A big server
 * can serve more values, smaller ones less. */
setting.maxHistoryDataResponseSize = 100;
```

**Comment by oroulet** [comment]
OK. We should make that configurable too then

**Comment by oroulet** [comment]
fixed it: https://github.com/FreeOpcUa/opcua-asyncio/pull/560

**Comment by oroulet** [comment]
merged

**Pull request closed without merging**
