### PR TITLE
Adding more sync functions

### PR DESCRIPTION
**Pull request by roin93**
Added the function I needed in the SyncWrapper.
The export_xml_by_ns() function is currently not working for me, but I am not sure if this is caused by the SyncWrapper or some other issue.

### CODE REVIEW

**Comment by oroulet** [comment]
Maybe i removed that export_by_ns? I kind of remember there was an issue with it 🤔

**Comment by roin93** [comment]
Feel free to remove it.

**Comment by oroulet** [comment]
I checked and it that method is away. Can you remove that line? it is much easier from you since you created the merge request

**Comment by swamper123** [comment]
@oroulet Do you mean that one?

https://github.com/FreeOpcUa/opcua-asyncio/blob/0a1cce0783d93493515ff92e55952e63909fc834/asyncua/server/server.py#L571

**Pull request merged**
