### PR TITLE
Replace os path with pathlib

### PR DESCRIPTION
**Pull request by ratara**
Hi,
I took the task to replace os.path with pathlib. I got trouble to run the unit tests, so you should run them to check for errors.

I also changed some type hinting and added a FIXME comment about a critical security vulnerability according to sonarlint.

### CODE REVIEW

**Comment by ratara** [comment]
Well, as mentioned in the other issue (https://github.com/FreeOpcUa/opcua-asyncio/issues/1160), I got the unit test running now.
I will run them now, after I solved the conflicts.

**Comment by ratara** [comment]
There are some unit test fails because of a weird re-use of variables with completely different types. Looks like a technical dept to my. I will take a look..

**Comment by schroeder-** [comment]
These changes are breaking the api. You should always accept both, str and path. Because in my opinion, this change is not worth breaking every application that is using this library.

**Comment by ratara** [comment]
> These changes are breaking the api. You should always accept both, str and path. Because in my opinion, this change is not worth breaking every application that is using this library.

I already added str and path support because the change broke tests. I will push a suggestion as soon as all tests pass.

**Comment by oroulet** [comment]
you need to rebase your branch.,
Also do we break compatibiliyt or not now?

**Comment by ratara** [comment]
image
@oroulet 
@schroeder-  is talking about the section in the screenshot. At first I changed that to Path because it was the obvious move but as @schroeder- is pointing out, this would break the API because at least the security string is used with this method directly. Someone else could use this method too with str. So I added str support again. But as you can see, this leads to a more complex is/else structure due to polymorphic use of that function.

It should work now. But maybe it would be nice if @schroeder- acknowledge that this was his point and that it is fine for him now.

**Comment by schroeder-** [comment]
Looks good 👍

**Comment by oroulet** [comment]
huum gitlabs says that branch is still outdated . Try `git pull --rebase  origin main`

**Comment by ratara** [comment]
> huum gitlabs says that branch is still outdated . Try `git pull --rebase origin main`

No, you just approved my other branch and we got a conflict here. Solved!

**Comment by oroulet** [comment]
I wrote my last comment before merging your other branch, and now I still cannot merge. gitlab tell med there is a conflict: 
image

**Comment by ratara** [comment]
> I wrote my last comment before merging your other branch, and now I still cannot merge. gitlab tell med there is a conflict: 
> image
> 

Ok, I try the rebase tomorrow.

**Comment by ratara** [comment]
:*-( 
I tried the rebase and got merge conflicts that result in a bad state where I got unit test fails. Strange thing is, I am getting errors in files I did not touch although the commits itself look like the ones of sql injection. I need more time(and focus) to recover from this.

**Pull request merged**
