### PR TITLE
Fix/publish callback

### PR DESCRIPTION
**Pull request by cbergmiller**
If i am not mistaken the `PublishResult` should always contain the `SubscriptionId` and we can use it to set `subscription_id` attribute if it is not set yet?

### CODE REVIEW

**Comment by oroulet** [comment]
This needs to be triple checked....

**Comment by oroulet** [comment]
I am quite sure this was added due to some race conditions....

**Comment by oroulet** [comment]
Now I remember, this is that you can get a publish result before we are finished creating the internal subscription object. Maybe this issue is away with asyncio but we really need to check there is no await before creation is finished

**Comment by cbergmiller** [comment]
`SubscriptionService.create_subscription` is synchronous but `InternalSession.create_subscription` is a coroutine (because in case of `UaClient` this is a async. network operation). How hard would it be to write a test that triggers the edge case of a publish result that gets emitted right on creation of the subscription?

**Comment by cbergmiller** [comment]
Fixed by 9591355706d357b8cf0db145aefc1167ed52bb6d

**Pull request closed without merging**
