### PR TITLE
Add sync_wrapper functions

### PR DESCRIPTION
**Pull request by okapies**
Add `sync_uaclient_method` and `sync_async_client_method` to use the underlying asynchronous methods while leveraging `sync.Client`.

### CODE REVIEW

**Comment by oroulet** [comment]
What issue does that code fix? I am a bit in a hurry but I could not understand.

**Comment by okapies** [comment]
There are some functionalities not implemented in the `sync` client (both async `Client` and `UaClient`). I want to use them directly combined with the thread loop run in the sync `Client`.

**Comment by oroulet** [comment]
we can have that method in addition, but why not adding the missing methods in the sync client?

**Comment by okapies** [comment]
Thanks for the merge. Because I finally found that I need to use `UaClient` directly for my use cases (e.g. handling detailed statuses for each item from the OPC server) in addition to #1369 and #1370.

**Pull request merged**
