### PR TITLE
Harding xml import

### PR DESCRIPTION
**Pull request by schroeder-**
Resolves error when import a VariableType with values #1256.
Encoding error when imported via client.
Respect datatypes in the sorting of import nodes.
Loading structs and enums directly on import, so these types can be used in the nodeset see #1248. 
Added a test for following companion specifications to verify the importer: DI, IA, , Scales, PackML, MachineVision.
Prevent endlessloop in sort nodes

### CODE REVIEW

**Comment by oroulet** [comment]
does that work? Should we restart tests?

**Comment by schroeder-** [comment]
Is still not complete. I keep working on it. Not to easy to keep all test working 😅.

**Comment by schroeder-** [comment]
Also not sure if we should realy add a 6mb nodeset for our test, maybe I look for a smaller companion specification with complex content.

**Comment by GoetzGoerisch** [comment]
> Also not sure if we should realy add a 6mb nodeset for our test, maybe I look for a smaller companion specification with complex content.

Which TypeDefinition are you specifically looking at in the CS named above?

We could add the OPC UA NodeSet repo as a git submodule like open62541 does.
- Benefit, always the latest released versions available

**Comment by schroeder-** [comment]
@GoetzGoerisch I just added Nodesets that i found in our issue tracker.

Removes TMC because we it has a Datatype MessageType, which collides with our internal datatype. 

```
@dataclass
class MessageType:
    Invalid: bytes = b'INV'  # FIXME: check value
    Hello: bytes = b'HEL'
    Acknowledge: bytes = b'ACK'
    Error: bytes = b'ERR'
    SecureOpen: bytes = b'OPN'
    SecureClose: bytes = b'CLO'
    SecureMessage: bytes = b'MSG'
```
Possibilities are to change rename or move the module of MessageType.
The extended possibility is to create a datatype with a added namespace like "MessageType_6", but this involves a lot of changes in our codebase.

**Comment by schroeder-** [comment]
Added the nodeset via github submodule. My only concern is that it will break our tests and block changes, if a nodeset changes. 
I am not a expert in git, is there a way use specific tag or revision for the submodule?

**Comment by GoetzGoerisch** [comment]
The gut commit which you added is fixed. Updates can be made manually or with automation via dependabot or renovate, which raises PR when ever there is an update upstream.

If this is desired I would contribute configuration for dependabot or renovate.

**Comment by schroeder-** [comment]
@GoetzGoerisch thanks for the clarification, create a dependabot configuration.

**Comment by oroulet** [comment]
please start name of MR with WIP: or Draft: if it is not finished. I am a bit confused here

**Comment by schroeder-** [comment]
It's finished now. There is only one nodeset not working because of a internal class we use. But this can make it into another pr.

**Pull request merged**
