### PR TITLE
Add type hints to Subscription

### PR DESCRIPTION
**Pull request by okapies**
- Add type hints to `Subscription`
- Add `SubscriptionHandler` protocol class for type hinting

### CODE REVIEW

**Comment by oroulet** [comment]
to solve that error. use `if typing.TYPE_CHECKING: import whatever for typing`

**Comment by okapies** [comment]
@oroulet Some tests failed because they pass `Node` to `subscribe_events` directly instead of `NodeId`:

https://github.com/FreeOpcUa/opcua-asyncio/blob/39e0710822ff178487b03f40fa22d8a6b8208289/tests/test_subscriptions.py#L733-L740

against the pydoc:

```python
    async def subscribe_events(
        ...
    ) -> int:
        """
        ...
        :param evtypes: ua.ObjectIds or ua.NodeId
```

Do you think we still need to support the `Nodes`, or fix the tests to pass `NodeId`?

**Comment by oroulet** [comment]
We have been supporting both for ages, so we should continue with it

**Comment by okapies** [comment]
Ok, I'll fix both the implementation and the type hint.

**Comment by okapies** [comment]
Thank you!

**Pull request merged**
