### PR TITLE
Lazy load lxml

### PR DESCRIPTION
**Pull request by joncutting**
Lazy load lxml to reduce frozen app size (>2MB) and save time at startup and for applications that don't require lxml processing. Should also speed up unit testing. Caveat - I have not run unit tests on this.

### CODE REVIEW

**Comment by oroulet** [comment]
Not sure what to think about that one... Quite a lot of code for a very special case

**Comment by oroulet** [comment]
Also it breaks all tests....

**Comment by oroulet** [comment]
The best would be to get rid of lxml ... Not much better that the build in stuff

**Comment by swamper123** [comment]
Since lxml was removed with #346 today, this PR is deprecated.

**Pull request closed without merging**
