### PR TITLE
Fixed exception on disconnect call of sync client. #146

### PR DESCRIPTION
**Pull request by TilmanK**

### CODE REVIEW

**Comment by oroulet** [comment]
Probably ok. But I do not think we should have a del method. One may want to have several clients using same loop

**Comment by TilmanK** [comment]
The loop is stopped in the __del__ method only if it was created in the __init__ method. AFAIK the __del__ method is exactly the place to handle such things created in __init__.

If a user wants to use the same loop on several Clients, he can pass that loop to the Client's constructor. In this case, the loop isn't stopped.

That's the intention I had when submitting the PR ;)

**Comment by oroulet** [comment]
OK. sorry I forgot that implicit loop creating existed... I am not sure it is a good idea.. but OK we have it

**Comment by TilmanK** [comment]
The implicit generation is more or less quite elegant. Just my 2 cents...

**Pull request merged**
