### PR TITLE
refactor

### PR DESCRIPTION
**Pull request by AndreasHeine**
-removed import
-used uatypes datetime

### CODE REVIEW

**Comment by oroulet** [comment]
I am not really sure what is the best thing to do here. I wrote these classes mainly for typing. And made them inherit python types because it was easy. But that was not used anywhere. You are writing the first use here.

**Comment by AndreasHeine** [comment]
currently messing around with the datavalue.ServerTimestamp = ua.DateTime.utcnow() is not set and causes "waiting for initial data" ...

**Comment by AndreasHeine** [comment]
```python
def value_to_datavalue(val, varianttype=None):
    """
    convert anyting to a DataValue using varianttype
    """
    if isinstance(val, ua.DataValue):
        datavalue = val
    elif isinstance(val, ua.Variant):
        datavalue = ua.DataValue(val)
        datavalue.SourceTimestamp = ua.DateTime.utcnow()
        # datavalue.ServerTimestamp = ua.DateTime.utcnow() # <--- causes "waiting for initial data" 
    else:
        datavalue = ua.DataValue(ua.Variant(val, varianttype))
        datavalue.SourceTimestamp = ua.DateTime.utcnow()
        # datavalue.ServerTimestamp = ua.DateTime.utcnow() # <--- causes "waiting for initial data" 
    return datavalue
```

**Comment by swamper123** [comment]
Something causes trouble. The ServerTime value itself looks like (from 11712 - "MaxNodesPerTranslateBrowsePathsToNodeIds"), an OperationalLimit Node):
grafik

But via UaExpert these are not browsable:
grafik

Could there be an error of how ServerTimestamp is structured?

**Pull request closed without merging**
