### PR TITLE
remove is_array argument from Variant, it is redundant, one can speci…

### PR DESCRIPTION
**Pull request by oroulet**
…fy Dimensions

### CODE REVIEW

**Comment by AndreasHeine** [comment]
@oroulet breaking change on next release!

**Comment by oroulet** [comment]
the problem is that I would like to avoid increasing main version number... not sure what to do

**Comment by AndreasHeine** [comment]
dont break the api ^^

**Comment by AndreasHeine** [comment]
add it to the release notes?

**Pull request merged**
