### PR TITLE
new approach to the new security token race condition

### PR DESCRIPTION
**Pull request by Randelung**
Alternative to #321, possible fix for #313.

Instead of making the receive loop async and using a lock, I use an extra field to pass request parameters (to the parse job) and result (for the return statement) back and forth, meaning there's a new condition of not being able to make a new request if the old one is still running.
Of course, a lock could be used to keep new requests waiting and execute them immediately after, but renewal this quickly is probably just not going to happen.

... he said foreshadowingly. *thunder cracks in the distance*

Forgot to mention that I tried to add_done_callback to the future, but that didn't work. It appears the callback is scheduled asynchronously.

### CODE REVIEW

**Comment by oroulet** [comment]
Does it fix the issue?

**Comment by oroulet** [comment]
@Randelung @AndreasHeine does that fix your issue?

**Comment by Randelung** [comment]
So far, I haven't detected any more issues on my end.

**Comment by oroulet** [comment]
this not so nice but I have no better idea for now

**Pull request merged**
